[tool.poetry]
name = "cypherman"
version = "0.0.0"
description = ""
authors = ["Kostiantyn <konstkadyr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.5"
fastapi = "^0.70.0"
uvicorn = {extras = ["standart"], version = "^0.15.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
