version: "3"

tasks:
  test:
    cmds:
      - poetry run pytest
    env:
      FASTAPI_CONFIGURATION: TESTING

  devserver:
    cmds:
      - docker-compose -f docker/docker-compose.yml --env-file docker/docker-compose.env up
