version: "3.8"

services:
  devserver:
    container_name: devserver
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    command: >
      uvicorn --host 0.0.0.0 --port 8000 --app-dir src/ --reload main:application
    ports:
      - "8000:8000"
    volumes:
      - "../src/app:/app/src:ro"
    env_file:
      - ../config/dev.env
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ../config/dev.env
