version: "3.8"

services:
  dev_server:
    container_name: dev_server
    profiles:
      - dev
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    command: >
      uvicorn --host 0.0.0.0 --port 8000 --app-dir src/ --reload main:application
    env_file:
      - ../config/dev.env
    ports:
      - "8000:8000"
    volumes:
      - "../src/app:/app/src:ro"
    depends_on:
      - dev_postgresql

  dev_postgresql:
    container_name: dev_postgresql
    image: postgres:14
    profiles:
      - dev
    env_file:
      - ../config/dev.env
    ports:
      - "5432:5432"

  test_app:
    container_name: test_app
    profiles:
      - test
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: test
    command: pytest $PYTEST_ARGS
    env_file:
      - ../config/test.env
    environment:
      - "PYTEST_ARGS=${PYTEST_ARGS}"
    volumes:
      - "../src/:/app/src:ro"
    depends_on:
      - test_postgresql

  test_postgresql:
    container_name: test_postgresql
    image: postgres:14
    profiles:
      - test
    env_file:
      - ../config/test.env
    # Expose ports only to a docker network
    ports:
      - "5432"
